# This is a basic workflow to help you get started with Actions

name: my-first-github-action
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{github.sha}}"
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my-first-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: first step of first job
        run: |
          echo "Hello, world from first job"
      - name: second step of first job
        run: |
          echo "Application name: ${{env.APPLICATION_NAME}}"
      - name: List current dir
        run: pwd
  
  my-second-job:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [my-first-job]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: first step of second job
        run: echo "Hello, world from second job"
      - name: Print deployment package name
        run: echo "Package name is ${{env.DEPLOY_PACKAGE_NAME}}"
